language:
  - ruby
  
env:
  - DB=mysql
  
before_script:
 - cd JBB-Web/
 - gem install rspec rspec-rails simplecov
 - bundle install
 - mysql -e 'create database my_app_test'
 
script: "RAILS_ENV=test bundle exec rake"

rvm:
  - 2.3.1
  
sudo: required 

notifications:
  email:
    recipients:
      - danieelteles@gmail.com
      - adailson2@gmail.com
      - gustavomn93@gmail.com
      - nicacionetobsb@gmail.com
      - iamferreirajp@gmail.com
